version: '3.6'

volumes:
  data:
  config:

services:
  rtf:
    build:
      context: ../../..
      dockerfile: ./ops/testnet/validator-node/Dockerfile
    restart: unless-stopped
    ports:
      - 30504:30504
      - 30303:30303
      - 30311:30311
      - 8545:8545
      - 8546:8546
      - 8575:8575
      - 8576:8576
    healthcheck:
      test: |
        [[ "$NETWORK" == "testnet" ]] && PORT=8575 || PORT=8545;
        netstat -tunlp | grep $PORT > /dev/null; if [ 0 != $$? ]; then exit 1; else exit 0; fi;

      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s
    volumes:
      - "data:/data"
      - "config:/rtf/config"
      - "../configs/config.toml:/rtf/config/config.toml"
    environment:
      - VALIDATOR_KEY
      - VALIDATOR_ADDRESS
      - NODE_KEY

