version: '3.6'

volumes:
  data:
  config:

services:
  rtf_t:
    build:
      context: ../../..
      dockerfile: ./ops/testnet/validator-node/Dockerfile
    restart: unless-stopped
    ports:
      - ${P2P_PORT}:${P2P_PORT}
    volumes:
      - "data:/data"
      - "config:/rtf/config"
      - "../configs/config.toml:/rtf/config/config.toml"
    environment:
      - VALIDATOR_KEY
      - VALIDATOR_ADDRESS
      - NODE_KEY
      - P2P_PORT

