version: '3.6'

volumes:
  data:
  config:

services:
  rtf_t:
    build:
      context: ../../..
      dockerfile: ./ops/testnet/rpc-node/Dockerfile
    restart: unless-stopped
    ports:
      - ${P2P_PORT}:${P2P_PORT}
      - ${RPC_PORT}:${RPC_PORT}
      - ${WS_PORT}:${WS_PORT}
    healthcheck:
      test: |
        netstat -tunlp | grep ${RPC_PORT} > /dev/null; if [ 0 != $$? ]; then exit 1; else exit 0; fi;
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s
    volumes:
      - "data:/data"
      - "config:/rtf/config"
      - "../configs/config.toml:/rtf/config/config.toml"
    environment:
      - P2P_PORT
      - RPC_PORT
      - WS_PORT

